---
title: "Intro to SQL: Querying"
author: "Zach Dravis"
date: 12.6.2017
output:
  md_document:
    variant: markdown_github
---

```{r, echo = F}
library(DBI)
db <- dbConnect(RSQLite::SQLite(), dbname = "sql.sqlite")
```


#SQL Notes
SQL --> "Structured Query Language"
A language for interacting with data stored in relational databases

#Part One: Working within a Table

##Terminology
Relational databases are a collection of tables
A row is a "record" and a column is a "field"
A query is a request for data from a database table or combination of tables

##SELECT statements
SELECT statements (go figure) select data from a table
```{sql, connection = db, eval = F}
SELECT name
FROM people;
```
This selects the name column from the people tables.

SELECT and FROM are keywords and are not case sensitive.  However, it is best practice to capitalize statements.
A semicolon indicates the end of a query.

So the basic structure for selecting a column from a table is:
```{sql, connection = db, eval = F}
SELECT ColumnName
FROM TableName;
```

You can also select multiple columns from a table at a time.
```{sql, connection = db, eval = F}
SELECT, column1, column2
FROM TableName;
```

You can also select all columns from a table without typing out all column names.
```{sql, connection = db, eval = F}
SELECT *
FROM TableName;
```

##Helpful Keywords
IF you want only a certain number of results (rows) to be returned, use the LIMIT keyword.
```{sql, connection = db, eval = F}
SELECT *
FROM TableName
LIMIT 10;
```
This is similar to the head() function in R.

To select all unique values from a column, use the DISTINCT keyword.
```{sql, connection = db, eval = F}
SELECT DISTINCT MyColumn FROM MyTable;
```
You can also write without creating a new line, like above.

To learn a count of all rows in a table, use the COUNT keyword.
```{sql, connection = db, eval = F}
SELECT COUNT(*) FROM MyTable;
```
This tells how many rows are in the table, but not how many non-missing values in a given column, like this does...
```{sql, connection = db, eval = F}
SELECT COUNT(Column1) FROM MyTable;
```
This returns the number of non-missing values in the specified column.

If you want to combine the distinct and count keywords to know the number of distinct values:
```{sql, connection = db, eval = F}
SELECT COUNT(DISTINCT column) FROM MyTable;
```


##Filtering results
WHERE keyword allows you to filter based on text and numeric values in a table
Comparison operators:
1. = equal
2. <> not equal
3. < less than
4. > greater than
5. <= less than or equal to
6. >= greater than or equal to

```{sql, connection = db, eval = F}
SELECT column1 FROM MyTable WHERE column1 = x;
```
So this code says, select column1 from table while column1 equals some given value (x)

If you wanted to get all columns from a table while a certain column equals a given value:
```{sql, connection = db, eval = F}
SELECT * FROM MyTable WHERE column1 = x;
```
This gives all the columns when column1 = x as opposed to the previous code that only gives column1 values when it is equal to x (which isn't really that useful)

If you want to select data based on multiple conditions, you can build up where queries by combining multiple conditions with the AND keyword.
```{sql, connection = db, eval = F}
SELECT column1 FROM MyTable WHERE column1 > x AND column 2 < y;
```

The OR operator is useful for selecting rows based on multiple conditions where some but not all of the conditions need to be met.
This is used the same way as the AND operator.
While using the AND operator along with the OR operator, you want to enclose each clause with brackets.
```{sql, connection = db, eval = F}
SELECT column3 FROM mytable WHERE (column1 = x OR column1 = y) AND (column2 = a OR column2 = b);
```

Selecting by ranges can be done with two and operators (ie with dates)
```{sql, connection = db, eval = F}
SELECT * FROM MyTable WHERE year > 1990 AND year < 2010
```

It can also be done more simply with the BETWEEN operator
The between operator is inclusive, so...
```{sql, connection = db, eval = F}
SELECT * FROM MyTable WHERE year BETWEEN 1990 AND 2010
```
This yields results from while year is 1990-2010 whereas the prior code yields results from while year is between 1991-2009

You can stack between with other AND/OR/BETWEEN statements:
```{sql, connection = db, eval = F}
SELECT name
FROM kids
WHERE age BETWEEN 2 AND 12
AND nationality = 'USA';
```

The WHERE operator can get unwieldy.  The IN operator helps by allowing to specify multiple OR values.
```{sql, connection = db, eval = F}
SELECT * FROM mytable WHERE col1 = 2 OR col1 = 4 OR col1 = 6...
```
Instead with the IN operator:
```{sql, connection = db, eval = F}
SELECT * FROM mytable WHERE col1 IN (2, 4, 6)
```

##NULL Values
In SQL, NULL represents missing or unknown values.  You can check for NULL using the expression IS NULL.
```{sql, connection = db, eval = F}
SELECT COUNT (*) FROM mytable WHERE column1 IS NULL;
```
This would return the number of null values in column1

IS NOT NULL operator will filter out null values
```{sql, connection = db, eval = F}
SELECT column1 FROM mytable WHERE column2 IS NOT NULL
```

##LIKE and NOT LIKE
The LIKE operator can be used in a WHERE clause to search for a pattern
Wildcards are used as a placeholder for some other values.
Here are two wildcards that can be used for LIKE: % and _
NOT LIKE operator is used to find records that don't match the pattern you specify

### %
```{sql, connection = db, eval = F}
SELECT name FROM people WHERE name Like 'Pe%';
```
This would return any name that began with Pe--Perry, Penelope, Percy, etc.

### _
This wildcard matches a single character
```{sql, connection = db, eval = F}
SELECT name FROM people WHERE name LIKE 'Per_y';
```
This would return any name in the specified column or table in which any letter replaces the underscore--Perry, Percy

##Aggregate Functions
Functions to help perform some calculations on data in a database.
*MIN
*MAX
*AVG
*SUM
```{sql, connection = db, eval = F}
SELECT SUM(length) FROM videos;
SELECT AVG(length) FROM videos;
SELECT MIN(length) FROM videos;
SELECT MAX(length) FROM videos;
```

Aggregate functions can also be combined with WHERE statements
```{sql, connection = db, eval = F}
SELECT AVG(cost)
FROM projects
WHERE project_date >= 2015;
```

##Arithmetic
Arithmetic can also be done
```{sql, connection = db, eval = F}
SELECT (3*4)
```
This would return 12.

However, be careful with dividing!
```{sql, connection = db, eval = F}
SELECT(4/3);
```
This would return 1 because you are dividing an integer by an integer and SQL rounds down (in this case) to provide you with an integer.
To fix this:
```{sql, connection = db, eval = F}
SELECT(4.0/3.0);
```
This would then provide 1.333

##The AS Keyword
When SQL performs a function, it returns a column with the name of the function:
```{sql, connection = db, eval = F}
SELECT MIN(field1) FROM mytable;
```
This would return the requested field (field1) as a column with the name "MIN"
This could get confusing when making two SELECTs with the same function:
```{sql, connection = db, eval = F}
SELECT MIN(field1), MIN(field2) FROM mytable;
```
This returns two columns, each with the name MIN.

Aliasing fixes this-->Assigning a temporary name to something.
Use the AS keyword to do this.
```{sql, connection = db, eval = F}
SELECT MIN(field1) as min_field1,
MIN(field2) as min_field2
FROM mytable;
```

##Ordering Results
ORDER BY keyword is used to sort results in ascending or descending order according to the valueso of one or more columns
Keywords for descending or ascending:
*DESC
*ASC
```{sql, connection = db, eval = F}
SELECT names
FROM presidents
ORDER BY height DESC;
```
In a table called "presidents" this code would sort the names of the presidents based on their height in descending order.  Therefore, the President with the oldest age would be returned first--Abraham Lincoln (followed by Lyndon B. Johnson all the way down to the shortest, James Madison)

When applied to text, ORDER BY will sort alphabetically A-Z

Can also order by multiple columns:
```{sql, connection = db, eval = F}
SELECT names
FROM presidents
ORDER BY height, age DESC;
```

##Grouping results
GROUP BY keyword allows you to group a result by one or more columns:
```{sql, connection = db, eval = F}
SELECT age, count(*)
FROM students
GROUP BY age;
```
This would provide a count for each age of the students in the "students" table.

You can also combine with order by to have the results returned in a particular order:
```{sql, connection = db, eval = F}
SELECT age, count(*)
FROM students
GROUP BY age
ORDER BY count DESC;
```

##HAVING clause
In SQL, you cannot use aggregate function in WHERE clauses
If you want to filter based on the result of an aggregate function (like SUM), you use the HAVING clause.
```{sql, connection = db, eval = F}
SELECT age
FROM presidents
GROUP BY age
HAVING COUNT(age) > 10;
```
This would return all of the presidents, grouped by age, for those age groups that have more than 10 presidents.

```{sql, connection = db, eval = F}
SELECT country, population, AVG(budget) AS avg_budget, AVG(state_pop) AS avg_state_pop
FROM countries
GROUP BY country
HAVING COUNT(population) > 10000
ORDER BY country
LIMIT 10;
```
So this code would return the first 10 countries ordered alphabetically with a population over 10,000 showing the average of different parts of their budget and the average of the state populations in that country.